feat/PRO-2696/wallet-connect
pillarwallet/x pull request #184
Opened 2024-09-26 16:41 UTC by RanaBug

## Description

-

## How Has This Been Tested?

-

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2025-02-18 14:59 UTC, IAmKio requested changes
Really good work - we finally got there after everything that has happened! The suggestions that i have left are mainly cosmetic, let me know if you have any questions! 🚀

2025-02-18 14:59 UTC, IAmKio commented on src/services/walletConnect.ts
> +        icons: [],
Can we reference the favicon or something similar here?

2025-02-18 14:59 UTC, IAmKio commented on src/services/walletConnect.ts
> +      } catch (e) {
We've referenced `e` but we're not using it - can at least `console.error` `e.message` here please

2025-02-18 14:59 UTC, IAmKio commented on src/services/walletConnect.ts
> +        } catch (e) {
As above please (re: `e`)

2025-02-18 14:59 UTC, IAmKio commented on src/services/walletConnect.ts
> +            subtitle: 'Connected via WalletConnect.',
```suggestion
            subtitle: 'Connected via WalletConnect',
```

2025-02-18 14:59 UTC, IAmKio commented on src/services/walletConnect.ts
> +            title: 'Something went wrong.',
```suggestion
            title: 'Something went wrong',
```
For consistency

2025-02-18 14:59 UTC, IAmKio commented on src/services/walletConnect.ts
> +        } catch (e) {
As above re: logging the error

2025-02-18 14:59 UTC, IAmKio commented on src/services/walletConnect.ts
> +      const dAppName = sessionData?.peer.metadata.name ?? 'dApp';
Might be worth defensively coding as you did above:

```suggestion
      const dAppName = sessionData?.peer?.metadata?.name ?? 'dApp';
```

2025-02-18 14:59 UTC, IAmKio commented on src/services/walletConnect.ts
> +      } catch (error) {
As above re: logging the error

2025-02-18 14:59 UTC, IAmKio commented on src/services/walletConnect.ts
> +          image: `${sessionData?.peer.metadata.icons[0]}`,
```suggestion
          image: `${sessionData?.peer?.metadata?.icons[0]}`,
```

2025-02-18 14:59 UTC, IAmKio commented on src/services/walletConnect.ts
> +          title: 'All sessions disconnected',
```suggestion
          title: 'WalletConnect,
```

2025-02-18 14:59 UTC, IAmKio commented on src/services/walletConnect.ts
> +          title: 'Unsuccessful disconnection',
```suggestion
          title: 'WalletConnect',
```

2025-02-18 14:59 UTC, IAmKio commented on src/services/walletConnect.ts
> +                chains: ['eip155:1', 'eip155:100', 'eip155:137', 'eip155:8453'],
If we are using testnets / staging mode - we need to add Sepolia here too

2025-02-18 14:59 UTC, IAmKio commented on src/services/walletConnect.ts
> +          }
As mentioned above, please add optional chaining to the metadata (as it may not exist) and all titles should be "WalletConnect" (we're repeating the content twice)

2025-02-18 14:59 UTC, IAmKio commented on src/services/walletConnect.ts
> +          title: 'Connection already exists',
As above re: title

2025-02-18 14:59 UTC, IAmKio commented on src/services/walletConnect.ts
> +      title: 'Connection ended',
As above re: title

2025-02-18 14:59 UTC, IAmKio commented on src/services/walletConnect.ts
> +        requestResponse = 'Transaction sent to PillarX wallet.';
Just a reminder:

```suggestion
        requestResponse = 'Transaction sent to PillarX';
```

2025-02-18 14:59 UTC, IAmKio commented on src/services/walletConnect.ts
> +      } catch (e: any) {
Please `console.error` the e please

2025-02-18 14:59 UTC, IAmKio commented on src/services/walletConnect.ts
> +          subtitle: 'The request has failed. Please try again.',
```suggestion
          title: 'WalletConnect',
          subtitle: 'The request has failed - there was a session request error. Please try again.',
```

2025-02-18 14:59 UTC, IAmKio commented on src/services/walletConnect.ts
> +          subtitle: 'The request has failed. Please try again.',
Please see suggestion above

2025-02-18 14:59 UTC, IAmKio commented on src/services/walletConnect.ts
> +      }
Please see suggestions above re: WalletConnect in the title and also please `console.error` the `e`

2025-02-18 15:02 UTC, RanaBug commented on src/apps/pillarx-app/components/WalletConnectDropdown/WalletConnectDropdown.tsx
> +      await connect(clipboardText);
Yes there is a lot of try catch within connect with the "toast" showing why it has errored, it is probably the place where you have the most try / catch and detailed errors that give to users :)

2025-02-18 15:06 UTC, RanaBug commented on src/apps/pillarx-app/components/WalletConnectModal/WalletConnectModal.tsx
> +  const appUrl = params?.proposer?.metadata?.url;
It does exists on the `ProposalTypes.Struct`, which is the type we are expecting to receive them. The ? is supposed to catch if it is undefined, and if it is, this component has things in place to not let it show as undefined.

2025-02-18 15:07 UTC, RanaBug commented on src/services/walletConnect.ts
> +        description: 'PillarX Wallet',
Oke, done!

2025-02-18 15:12 UTC, RanaBug commented on src/services/walletConnect.ts
> +      } catch (e) {
You are right, done

2025-02-18 15:13 UTC, RanaBug commented on src/services/walletConnect.ts
> +        } catch (e) {
Done

2025-02-18 15:13 UTC, RanaBug commented on src/services/walletConnect.ts
> +            subtitle: 'Connected via WalletConnect.',
Done

2025-02-18 15:14 UTC, RanaBug commented on src/services/walletConnect.ts
> +            title: 'Something went wrong.',
Done

2025-02-18 15:14 UTC, RanaBug commented on src/services/walletConnect.ts
> +        } catch (e) {
Done

2025-02-18 15:15 UTC, RanaBug commented on src/services/walletConnect.ts
> +      const dAppName = sessionData?.peer.metadata.name ?? 'dApp';
You are right, done

2025-02-18 15:16 UTC, RanaBug commented on src/services/walletConnect.ts
> +      } catch (error) {
Done

2025-02-18 15:17 UTC, RanaBug commented on src/services/walletConnect.ts
> +          title: 'All sessions disconnected',
Mmmm why?

2025-02-18 15:19 UTC, RanaBug commented on src/services/walletConnect.ts
> +          title: 'All sessions disconnected',
Done

2025-02-18 15:19 UTC, RanaBug commented on src/services/walletConnect.ts
> +          title: 'Unsuccessful disconnection',
Done

2025-02-18 15:31 UTC, RanaBug commented on src/services/walletConnect.ts
> +          }
All done

2025-02-18 15:32 UTC, RanaBug commented on src/services/walletConnect.ts
> +      title: 'Connection ended',
Done

2025-02-18 15:34 UTC, RanaBug commented on src/services/walletConnect.ts
> +      } catch (e: any) {
Done

2025-02-18 15:35 UTC, RanaBug commented on src/services/walletConnect.ts
> +          subtitle: 'The request has failed. Please try again.',
Done

2025-02-18 15:35 UTC, RanaBug commented on src/services/walletConnect.ts
> +          subtitle: 'The request has failed. Please try again.',
Done

2025-02-18 15:37 UTC, RanaBug commented on src/services/walletConnect.ts
> +      }
Done

2025-02-18 23:23 UTC, IAmKio commented on src/apps/pillarx-app/components/WalletConnectModal/WalletConnectModal.tsx
> +  const appName = params?.proposer?.metadata?.name || 'Unknown app';
Thank you!

2025-02-18 23:23 UTC, IAmKio commented on src/apps/pillarx-app/components/WalletConnectModal/WalletConnectModal.tsx
> +  const appUrl = params?.proposer?.metadata?.url;
Got it thanks!

2025-02-18 23:31 UTC, IAmKio requested changes
Just a few additional comments but we're nearly there ✨

2025-02-18 23:31 UTC, IAmKio commented on src/services/walletConnect.ts
> +        icons: ['/favicon.ico'],
Does this need to be a fully qualified URL? For example if this is the data that is sent to another dApp, would the icon try to load the favicon.ico on the _remote_ website?

2025-02-18 23:31 UTC, IAmKio commented on src/services/walletConnect.ts
> +                  'eip155:8453',
I just remembered do we not have a util or dictionary somewhere of what networks are currently supported on Px which takes into account the environment also? I'm just wondering if this will be easier because:

- We may broadcast a network that's not currently available in staging / production or the other way around
- If and when we add another supported network, we would have to come back here and update this list manually

Let me know!

2025-02-18 23:31 UTC, IAmKio commented on src/services/walletConnect.ts
> +                  `eip155:11155111:${wallet}`,
See comment above 🙏

2025-02-19 08:48 UTC, RanaBug commented on src/services/walletConnect.ts
> +                  'eip155:8453',
Not at the moment, but I think this should definitively be done for the whole app - could we do this in a ticket as this will also affect other part of the apps and other pillarx apps as well?

2025-02-19 08:48 UTC, RanaBug commented on src/services/walletConnect.ts
> +                  `eip155:11155111:${wallet}`,
Responded above

2025-02-19 08:52 UTC, RanaBug commented on src/services/walletConnect.ts
> +        icons: ['/favicon.ico'],
You are right, I've changed it to: https://pillarx.app/favicon.ico

2025-02-19 09:04 UTC, IAmKio commented on src/services/walletConnect.ts
> +                  'eip155:8453',
Yes let's get this in as a ticket - apologies i thought it was there already!

2025-02-19 09:04 UTC, IAmKio approved these changes
LGTM! This is a huge milestone 🧦

2025-02-19 09:05 UTC, merged