feat/PRO-2905/Points-Tile
pillarwallet/x pull request #220
Opened 2024-12-19 15:42 UTC by RanaBug

## Description

- Points tile frontend implementation

## How Has This Been Tested?

- Unit tests and manual testing

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2025-01-03 13:07 UTC, IAmKio commented on src/apps/pillarx-app/components/PointsFormattedTimestamp/PointsFormattedTimestamp.tsx
> +  const minutes = Math.floor((totalSeconds % 3600) / 60);
Just a note, luxon library might help you better in future 🙏

2025-01-03 13:29 UTC, IAmKio requested changes
Just a minor point but other than that looks good!

2025-01-03 13:29 UTC, IAmKio commented on src/apps/pillarx-app/components/PointsTile/PointsTile.tsx
> +          <div className="flex desktop:flex-col tablet:flex-row mobile:flex-row desktop:w-[25%] tablet:w-full mobile:w-full h-full bg-container_grey/[.9] rounded-[10px] p-4 pt-8 justify-between gap-4
Could we make this conditional please on the referal data existing? When we launch this it likely won't exist so we need to hide this column for now

2025-01-03 13:29 UTC, IAmKio commented on src/apps/pillarx-app/components/PointsTile/test/PointsTile.test.tsx
> +  });
Just a note to add a test to hide referals section when not available

2025-01-07 17:48 UTC, RanaBug commented on src/apps/pillarx-app/components/PointsTile/PointsTile.tsx
> +          <div className="flex desktop:flex-col tablet:flex-row mobile:flex-row desktop:w-[25%] tablet:w-full mobile:w-full h-full bg-container_grey/[.9] rounded-[10px] p-4 pt-8 justify-between gap-4
Ok no worries I added a condition if no code AND no href, then it does not show

2025-01-07 18:01 UTC, RanaBug commented on src/apps/pillarx-app/components/PointsTile/test/PointsTile.test.tsx
> +  });
Done

2025-01-07 20:30 UTC, IAmKio approved these changes
LGTM!

2025-01-08 09:14 UTC, merged