Stealthex new app
pillarwallet/x pull request #90
Opened 2024-06-21 10:34 UTC by DazkStealth

## Description
- Adding Stealthex app with its widget.
## How Has This Been Tested?
- Checked widget operation with a test swap
## Screenshots (if appropriate):

## Types of changes
Adding new app that includes https://www.npmjs.com/package/@stealthex-io/widget

2024-07-22 12:30 UTC, IAmKio commented
@DazkStealth do you mind pulling the latest staging into your project please as there are conflicts currently - thank you!

2024-07-22 12:43 UTC, DazkStealth commented
@IAmKio sry haven`t noticed. Done it!

2024-07-22 14:05 UTC, IAmKio commented
@DazkStealth could you please check the styling naming you're using - once we load your app and then go back to the home feed or open any of the Action Bar menus - the text styles / backgrounds etc have all been overridden. Please see the screenshot below:

![Screenshot 2024-07-22 at 15 02 17](https://github.com/user-attachments/assets/acd4879c-6439-44bc-80b5-e2ac3ea5eca8)

2024-07-23 13:37 UTC, IAmKio commented
@DazkStealth thanks again for your updated submission - we just noticed that you've overridden the `html` style in the global.css file, could you please remove / comment it out and move that style to your application scope please?

https://github.com/pillarwallet/x/pull/90/commits/9cd2ea0f09969d9ca4c6b55b11ffd0e364c988ba#diff-d9cbf41d20b9faa34b9066b78856527aca74367f903adf9fc5b00d03bbab0191R34

2024-07-24 10:46 UTC, DazkStealth commented
@IAmKio so i think it`s done.

2024-08-01 14:55 UTC, IAmKio requested changes
We're nearly there just a few questions and suggestions - thank you!

2024-08-01 14:55 UTC, IAmKio commented on src/apps/stealthex/lib/styles/resets.css
Can we remove this reset please, our own global styles system should be responsible for this

2024-08-01 14:55 UTC, IAmKio commented on src/apps/stealthex/lib/styles/simplex.css
> +iframe[id*='simplex-iframe'] {
I think this answers my question above

2024-08-01 15:23 UTC, IAmKio commented
@DazkStealth finally made it through the review - just a few questions, we're nearly there!

2024-08-05 10:08 UTC, DazkStealth commented
@IAmKio Hey! I`ve done what you requested. Apologies for the delay.

2024-08-07 05:28 UTC, IAmKio commented
@DazkStealth could you please check this error we got whilst running the code checks in this branch:

```[eslint] 
src/apps/stealthex/components/exchange/swap/input/index.tsx
  Line 74:8:  React Hook useEffect has a missing dependency: 'pressable'. Either include it or remove the dependency array  react-hooks/exhaustive-deps```

Thanks!

2024-08-07 11:57 UTC, DazkStealth commented
@IAmKio it's done!

2024-08-07 12:00 UTC, IAmKio commented
> @IAmKio it's done!

Re-running checks...

2024-08-07 12:14 UTC, IAmKio approved these changes
LGTM - thanks for being our first app within the PillarX ecosystem! LFG!!! 🚀 Our QA team will test this once it's merged - feel free to merge this when you're ready

2024-08-08 10:06 UTC, DazkStealth commented
@IAmKio Looks like i do not have write access to merge it. Can you help me?

2024-08-08 10:12 UTC, merged

2024-08-08 10:13 UTC, IAmKio commented
@DazkStealth done ✨